CREATE DIRECTORY MYDIR AS 'C:\TESTLOC';
DECLARE
  L_HANDLER UTL_FILE.FILE_TYPE;
BEGIN
  L_HANDLER := UTL_FILE.FOPEN('MYDIR', 'SYS.txt', 'W');
  UTL_FILE.PUTF(L_HANDLER, 'UTL_FILE write mode demonstration');
  UTL_FILE.FCLOSE(L_HANDLER);
END;
